answer/urls.py
from django.urls import path
from . import views

app_name = 'answer'

urlpatterns = [
    path('', views.AnswerTop.as_view(), name='top'),
    path('register', views.AnswerRegister.as_view(), name='register'),
    path('register_complete', views.AnswerRegisterComplete.as_view(), name='register_complete'),
    path('update/<int:pk>', views.AnswerUpdate.as_view(), name='update'),
    path('update_complete', views.AnswerUpdateComplete.as_view(), name='update_complete'),
    path('delete/<int:pk>', views.AnswerDelete.as_view(), name='delete'),
]

jobchange/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('company/', include('company.urls')),
    path('interview/', include('interview.urls')),
    path('answer/', include('answer.urls')),
]

answer/models.py
from django.db import models
from register.models import User

class Answer(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.TextField(null=True, blank=True)
    answer = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

answer/forms.py
from django import forms
from .models import Answer

class AnswerRegisterForm(forms.ModelForm):

    class Meta:
        model = Answer
        fields = (
            'question',
            'answer',
        )

    question = forms.CharField(
        label='質問',
        required=False,
        widget=forms.Textarea(attrs={'placeholder': '質問', 'class': 'form-control'})
    )
    answer = forms.CharField(
        label='回答',
        required=False,
        widget=forms.Textarea(attrs={'placeholder': '回答', 'class': 'form-control'})
    )

class AnswerUpdateForm(forms.ModelForm):

    class Meta:
        model = Answer
        fields = (
            'question',
            'answer',
        )

    question = forms.CharField(
        label='質問',
        required=False,
        widget=forms.Textarea(attrs={'placeholder': '質問', 'class': 'form-control'})
    )
    answer = forms.CharField(
        label='回答',
        required=False,
        widget=forms.Textarea(attrs={'placeholder': '回答', 'class': 'form-control'})
    )

answer/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.shortcuts import redirect
from django.views import generic
from .models import Answer
from .forms import AnswerRegisterForm, AnswerUpdateForm

User = get_user_model()

class AnswerTop(generic.TemplateView):
    template_name = 'answer/top.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        login_user = self.request.user
        context['answeres'] = Answer.objects.filter(user_id=login_user).values
        return context


class AnswerRegister(generic.View):
    form_class = AnswerRegisterForm
    template_name = 'answer/answer_register.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            login_user = request.user
            question = form.cleaned_data['question']
            answer = form.cleaned_data['answer']
            Answer.objects.create(
                user_id=login_user,
                question=question,
                answer=answer
            )
            return render(request, 'answer/answer_register_complete.html')
        return render(request, self.template_name, {'form': form})


class AnswerRegisterComplete(generic.TemplateView):
    template_name = 'answer/answer_register_complete.html'


class AnswerUpdate(generic.TemplateView):
    form_class = AnswerUpdateForm
    template_name = 'answer/answer_update.html'

    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        answer = Answer.objects.get(id=pk)
        form = self.form_class(instance=answer)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            answer = form.cleaned_data['answer']
            question = form.cleaned_data['question']
            pk = self.kwargs['pk']
            answer_obj = Answer.objects.get(id=pk)
            answer_obj.answer = answer
            answer_obj.question = question
            answer_obj.save()
            return redirect('answer:update_complete')
        return render(request, self.template_name, {'form': form})


class AnswerUpdateComplete(generic.TemplateView):
    template_name = 'answer/answer_update_complete.html'


class AnswerDelete(generic.TemplateView):
    template_name = 'answer/answer_delete_complete.html'

    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        Answer.objects.get(id=pk).delete()
        return render(request, self.template_name)

answer/templates/answer/answer_delete_complete.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">面接質問・回答削除</h2>
            <p>質問・回答削除が完了しました。</p>
            <a href='{% url 'answer:top' %}'>質問・回答一覧へ</a>
        </div>
    </div>
</div>
{% endblock %}

answer/templates/answer/answer_register.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">面接質問・回答登録</h2>
            <p>面接時によく聞かれる質問とそれに対する自分の回答を登録しておき、随時見直して、ブラッシュアップしてみましょう！</p>
            <form method="post" action="">
            {% csrf_token %}
                <div class="form-group">
                    <p>{{ form.errors.question }}</p>
                  　<label for="company_name">{{form.question.label}}</label>
                  　{{form.question}}
              　</div>
                <div class="form-group">
                　  <p>{{ form.errors.answer }}</p>
                  　<label for="company_name">{{form.answer.label}}</label>
                  　{{form.answer}}
              　</div>
              <button type="submit" class="btn btn-success btn-lg btn-block">登録</button>
              <a href='{% url 'answer:top' %}' class="login_link">質問・回答一覧へ</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

answer/templates/answer/answer_register_complete.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">面接質問・回答登録</h2>
            <p>質問・回答登録が完了しました。</p>
            <a href='{% url 'answer:top' %}'>質問・回答一覧へ</a>
        </div>
    </div>
</div>
{% endblock %}

answer/templates/answer/answer_update.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">面接質問・回答編集</h2>
            <p>面接時によく聞かれる質問とそれに対する自分の回答を登録しておき、随時見直して、ブラッシュアップしてみましょう！</p>
            <form method="post" action="">
            {% csrf_token %}
                <div class="form-group">
                    <p>{{ form.errors.question }}</p>
                  　<label for="company_name">{{form.question.label}}</label>
                  　{{form.question}}
              　</div>
                <div class="form-group">
                　  <p>{{ form.errors.answer }}</p>
                  　<label for="company_name">{{form.answer.label}}</label>
                  　{{form.answer}}
              　</div>
              <button type="submit" class="btn btn-success btn-lg btn-block">変更</button>
              <a href='{% url 'answer:top' %}' class="login_link">質問・回答一覧へ</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

answer/templates/answer/answer_update_complete.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">面接質問・回答編集</h2>
            <p>質問・回答変更が完了しました。</p>
            <a href='{% url 'answer:top' %}'>質問・回答一覧へ</a>
        </div>
    </div>
</div>
{% endblock %}

answer/templates/answer/top.html
{% extends "register/base.html" %}
{% block content %}
    <h2 class="login_title">面接質問・回答登録</h2>
    <p class="text-center main_contets margin_auto">面接時によく聞かれる質問とそれに対する自分の回答を登録しておき、随時見直して、ブラッシュアップしてみましょう！</p>
    <a class="btn btn-primary register_button_margin" href="{% url "answer:register" %}" role="button">新規登録</a>
    {% if answeres %}
    {% for answer in answeres %}
        <div class="card bg-light mb-3 margin_auto main_contets">
          <h5 class="card-header text-center">
              {% if answer.question %}
                  　{{ answer.question }}
              　{% else %}
                  　登録なし
              　{% endif %}
          </h5>
          <div class="card-body">
            <p class="card-text">
                {% if answer.answer %}
                  　{{ answer.answer }}
              　{% else %}
                  　登録なし
              　{% endif %}
            </p>
            <a class="btn btn-warning" href="{% url "answer:update" answer.id %}" role="button">変更</a>
          　<a class="btn btn-danger" href="#" role="button" data-toggle="modal" data-target="#exampleModal{{ answer.id }}">削除</a>

              <!-- 削除モーダル -->
                <div class="modal fade" id="exampleModal{{ answer.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">削除確認</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                          {% if answer.question %}
                              「{{ answer.question }}」を本当に削除しますか？
                          {% else %}
                              本当に削除しますか？
                          {% endif %}
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
                        <a class="btn btn-danger" href="{% url "answer:delete" answer.id %}" role="button">削除</a>
                      </div>
                    </div>
                  </div>
                </div>

          </div>
        </div>
    {% endfor %}
    {% else %}
        <p class="text-center main_contets margin_auto">データがありません。</p>
    {% endif %}
{% endblock %}