answer/urls.py
from django.urls import path
from . import views

app_name = 'answer'

urlpatterns = [
    path('', views.AnswerTop.as_view(), name='top'),
    path('register', views.AnswerRegister.as_view(), name='register'),
    path('register_complete', views.AnswerRegisterComplete.as_view(), name='register_complete'),
    path('update/<int:pk>', views.AnswerUpdate.as_view(), name='update'),
    path('update_complete', views.AnswerUpdateComplete.as_view(), name='update_complete'),
    path('delete/<int:pk>', views.AnswerDelete.as_view(), name='delete'),
]

company/urls.py
from django.urls import path
from . import views

app_name = 'company'

urlpatterns = [
    path('', views.CompanyTop.as_view(), name='top'),
    path('register', views.CompanyRegister.as_view(), name='register'),
    path('register_complete', views.CompanyRegisterComplete.as_view(), name='register_complete'),
    path('update/<int:pk>', views.CompanyUpdate.as_view(), name='update'),
    path('update_complete', views.CompanyUpdateComplete.as_view(), name='update_complete'),
    path('delete/<int:pk>', views.CompanyDelete.as_view(), name='delete'),
]

jobchange/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('company/', include('company.urls')),
    path('interview/', include('interview.urls')),
    path('answer/', include('answer.urls')),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('', views.Top.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
]

register/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager


class UserManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def username(self):
        return self.email

register/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm, PasswordChangeForm,
    PasswordResetForm, SetPasswordForm
)
from django.contrib.auth import get_user_model

User = get_user_model()


class LoginForm(AuthenticationForm):
    """ログインフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

class UserCreateForm(UserCreationForm):
    """ユーザー登録用フォーム"""

    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email

class MyPasswordChangeForm(PasswordChangeForm):
    """パスワード変更フォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class MyPasswordResetForm(PasswordResetForm):
    """パスワード忘れたときのフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class MySetPasswordForm(SetPasswordForm):
    """パスワード再設定用フォーム(パスワード忘れて再設定)"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class EmailChangeForm(forms.ModelForm):
    """メールアドレス変更フォーム"""

    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email

register/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import Http404, HttpResponseBadRequest
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.template.loader import render_to_string
from django.views import generic
from .forms import (
    LoginForm, UserCreateForm, MyPasswordChangeForm,
    MyPasswordResetForm, MySetPasswordForm, EmailChangeForm
)

User = get_user_model()

class Top(generic.TemplateView):
    template_name = 'register/top.html'

class Login(LoginView):
    """ログイン"""
    form_class = LoginForm
    template_name = 'register/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    """ログアウト"""
    template_name = 'register/logout.html'


class UserCreate(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'register/user_create.html'
    form_class = UserCreateForm

    def form_valid(self, form):
        """仮登録と本登録用メールの発行"""
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject = render_to_string('register/mail_template/create/subject.txt', context)
        message = render_to_string('register/mail_template/create/message.txt', context)

        user.email_user(subject, message)
        return redirect('register:user_create_done')


class UserCreateDone(generic.TemplateView):
    """ユーザー仮登録完了"""
    template_name = 'register/user_create_done.html'


class UserCreateComplete(generic.TemplateView):
    """ユーザー本登録"""
    template_name = 'register/user_create_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        except SignatureExpired:
            return HttpResponseBadRequest()

        except BadSignature:
            return HttpResponseBadRequest()

        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()

class PasswordChange(PasswordChangeView):
    """パスワード変更"""
    form_class = MyPasswordChangeForm
    success_url = reverse_lazy('register:password_change_done')
    template_name = 'register/password_change.html'

class PasswordChangeDone(PasswordChangeDoneView):
    """パスワード変更完了"""
    template_name = 'register/password_change_done.html'

class PasswordReset(PasswordResetView):
    """パスワード変更用URLの送付"""
    subject_template_name = 'register/mail_template/password_reset/subject.txt'
    email_template_name = 'register/mail_template/password_reset/message.txt'
    template_name = 'register/password_reset_form.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('register:password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    """パスワード変更用URL送付完了"""
    template_name = 'register/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    """新パスワード入力"""
    form_class = MySetPasswordForm
    success_url = reverse_lazy('register:password_reset_complete')
    template_name = 'register/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    """新パスワード設定完了"""
    template_name = 'register/password_reset_complete.html'

class EmailChange(LoginRequiredMixin, generic.FormView):
    """メールアドレス変更"""
    template_name = 'register/email_change_form.html'
    form_class = EmailChangeForm

    def form_valid(self, form):
        user = self.request.user
        new_email = form.cleaned_data['email']

        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': 'https' if self.request.is_secure() else 'http',
            'domain': domain,
            'token': dumps(new_email),
            'user': user,
        }

        subject = render_to_string('register/mail_template/email_change/subject.txt', context)
        message = render_to_string('register/mail_template/email_change/message.txt', context)
        send_mail(subject, message, None, [new_email])

        return redirect('register:email_change_done')


class EmailChangeDone(LoginRequiredMixin, generic.TemplateView):
    """メールアドレス変更メール送信完了"""
    template_name = 'register/email_change_done.html'


class EmailChangeComplete(LoginRequiredMixin, generic.TemplateView):
    """メールアドレス変更完了"""
    template_name = 'register/email_change_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        token = kwargs.get('token')
        try:
            new_email = loads(token, max_age=self.timeout_seconds)

        except SignatureExpired:
            return HttpResponseBadRequest()

        except BadSignature:
            return HttpResponseBadRequest()

        else:
            User.objects.filter(email=new_email, is_active=False).delete()
            request.user.email = new_email
            request.user.save()
            return super().get(request, **kwargs)

register/templates/register/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'register/style.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <title>面接日記</title>
</head>
<body>
    <!-- ナビゲーション -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand font-weight-bold" href="{% url 'company:top' %}">面接日記</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <li>
            <a class="nav-item nav-link" href="{% url 'company:top' %}">面接企業一覧</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'company:register' %}">面接企業登録</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'answer:top' %}">面接質問・回答登録</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:email_change' %}">メールアドレスの変更</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:password_change' %}">パスワードの変更</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:logout' %}">ログアウト</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'register:login' %}">
            ログイン
          </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <!-- メイン -->
    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
</body>
</html>

register/templates/register/base_auth.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'register/style.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <title>面接日記</title>
</head>
<body>

    <!-- メイン -->
    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
</body>
</html>

register/templates/register/email_change_done.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">メールアドレス変更</h2>
            <p>
                確認メールに記載されているリンクをクリックすると、アドレスが変更されます。
            </p>
        </div>
    </div>
</div>
{% endblock %}

register/templates/register/email_change_form.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">メールアドレス変更</h2>
            <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}
                {% csrf_token %}
                <button type="submit" class="btn btn-success btn-lg btn-block">送信</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

register/templates/register/login.html
{% extends "register/base_auth.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">ログイン</h2>
            <form action="{% url 'register:login' %}" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <hr class="hr">
                {% endfor %}
                <a href="{% url 'register:password_reset' %}" class="login_link" >パスワードを忘れた方</a>
                <button type="submit" class="btn btn-success btn-lg btn-block" >ログイン</button>
                <input type="hidden" name="next" value="{{ next }}" />
                <a href="{% url 'register:user_create' %}" class="login_link" >会員登録がまだの方</a>
                {% csrf_token %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

register/templates/register/logout.html
{% extends "register/base_auth.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">ログアウト</h2>
            <p>
                ログアウトしました。<br>
                <a class="" href="{% url 'register:login' %}">ログインはこちら</a>
            </p>
        </div>
    </div>
</div>
{% endblock %}

register/templates/register/password_change.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">パスワード変更</h2>
            <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}
                {% csrf_token %}
                <button type="submit" class="btn btn-success btn-lg btn-block">送信</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

register/templates/register/password_change_done.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">パスワード再設定</h2>
            <p>
                パスワードを変更しました。<br>
                <a class="" href="{% url 'register:login' %}">ログイン</a>
            </p>
        </div>
    </div>
</div>
{% endblock %}

register/templates/register/password_reset_confirm.html
{% extends "register/base_auth.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">パスワード再設定</h2>
            <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}
                {% csrf_token %}
                <button type="submit" class="btn btn-success btn-lg btn-block">送信</button>
                <a class="login_link" href="{% url 'register:login' %}">ログインはこちら</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

register/templates/register/password_reset_done.html
{% extends "register/base_auth.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">パスワード再設定</h2>
            <p>
                パスワード再設定用のメールを送信しました。<br>
                メールに記載されているリンクから再設定を行ってください。
                <a class="" href="{% url 'register:login' %}">ログインはこちら</a>
            </p>
        </div>
    </div>
</div>
{% endblock %}

register/templates/register/password_reset_form.html
{% extends "register/base_auth.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">パスワード再設定</h2>
             <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}
                {% csrf_token %}
                <button type="submit" class="btn btn-success btn-lg btn-block">送信</button>
                <a class="login_link" href="{% url 'register:login' %}">ログインはこちら</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

register/templates/register/top.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'register/style.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <title>面接日記</title>
</head>
<body>
<div class="top">
    <div class="top_contents">
    <h2 class="top_title">面接日記</h2>
    <a class="btn btn-info btn-lg top_button" href="{% url 'register:login' %}" role="button">ログイン画面へ</a>
    </div>
</div>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
</body>
</html>

register/templates/register/user_create.html
{% extends "register/base_auth.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">会員登録</h2>
            <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}
                {% csrf_token %}
                <button type="submit" class="btn btn-success btn-lg btn-block">送信</button>
                <a href="{% url 'register:login' %}" class="login_link" >ログインはこちら</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

register/templates/register/user_create_complete.html
{% extends "register/base_auth.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">会員登録</h2>
            <p>
                ユーザー登録を完了しました。<br>
                <a class="" href="{% url 'register:login' %}">ログインはこちら</a>
            </p>
        </div>
    </div>
</div>
{% endblock %}