answer/urls.py
from django.urls import path
from . import views

app_name = 'answer'

urlpatterns = [
    path('', views.AnswerTop.as_view(), name='top'),
    path('register', views.AnswerRegister.as_view(), name='register'),
    path('register_complete', views.AnswerRegisterComplete.as_view(), name='register_complete'),
    path('update/<int:pk>', views.AnswerUpdate.as_view(), name='update'),
    path('update_complete', views.AnswerUpdateComplete.as_view(), name='update_complete'),
    path('delete/<int:pk>', views.AnswerDelete.as_view(), name='delete'),
]

company/urls.py
from django.urls import path
from . import views

app_name = 'company'

urlpatterns = [
    path('', views.CompanyTop.as_view(), name='top'),
    path('register', views.CompanyRegister.as_view(), name='register'),
    path('register_complete', views.CompanyRegisterComplete.as_view(), name='register_complete'),
    path('update/<int:pk>', views.CompanyUpdate.as_view(), name='update'),
    path('update_complete', views.CompanyUpdateComplete.as_view(), name='update_complete'),
    path('delete/<int:pk>', views.CompanyDelete.as_view(), name='delete'),
]

interview/urls.py
from django.urls import path
from . import views

app_name = 'interview'

urlpatterns = [
    path('<int:pk>', views.InterviewTop.as_view(), name='top'),
    path('register/<int:pk>', views.InterviewRegister.as_view(), name='register'),
    path('register_complete', views.InterviewRegisterComplete.as_view(), name='register_complete'),
    path('update/<int:pk>', views.InterviewUpdate.as_view(), name='update'),
    path('update_complete', views.InterviewUpdateComplete.as_view(), name='update_complete'),
    path('delete/<int:pk>', views.InterviewDelete.as_view(), name='delete'),
]

jobchange/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('company/', include('company.urls')),
    path('interview/', include('interview.urls')),
    path('answer/', include('answer.urls')),
]

company/models.py
from django.db import models
from register.models import User

class Company(models.Model):
    company_name = models.CharField(max_length=200)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

company/forms.py
from django import forms
from .models import Company

class CompanyRegisterForm(forms.Form):
    company_name = forms.CharField(
        label='企業名',
        max_length=200,
        required=True,
        widget=forms.TextInput(attrs={'placeholder':'企業名', 'class':'form-control'})
    )

class CompanyUpdateForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ('company_name',)

    company_name = forms.CharField(
        label='企業名',
        max_length=200,
        required=True,
        widget=forms.TextInput(attrs={'placeholder':'企業名', 'class':'form-control'})
    )

company/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.shortcuts import redirect
from django.views import generic
from .models import Company
from .forms import CompanyRegisterForm, CompanyUpdateForm

User = get_user_model()

class CompanyTop(generic.TemplateView):
    template_name = 'company/top.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        login_user = self.request.user
        context['companies'] = Company.objects.filter(user_id=login_user).values
        return context


class CompanyRegister(generic.View):
    form_class = CompanyRegisterForm
    template_name = 'company/company_register.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            company_name = form.cleaned_data['company_name']
            login_user = request.user
            Company.objects.create(company_name=company_name, user_id=login_user)
            return redirect('company:register_complete')
        return render(request, self.template_name, {'form': form})


class CompanyRegisterComplete(generic.TemplateView):
    template_name = 'company/company_register_complete.html'


class CompanyUpdate(generic.TemplateView):
    form_class = CompanyUpdateForm
    template_name = 'company/company_update.html'

    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        company = Company.objects.get(id=pk)
        form = self.form_class(instance=company)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            company_name = form.cleaned_data['company_name']
            pk = self.kwargs['pk']
            company = Company.objects.get(id=pk)
            company.company_name = company_name
            company.save()
            return redirect('company:update_complete')
        return render(request, self.template_name, {'form': form})


class CompanyUpdateComplete(generic.TemplateView):
    template_name = 'company/company_update_complete.html'


class CompanyDelete(generic.TemplateView):
    template_name = 'company/company_delete_complete.html'

    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        Company.objects.get(id=pk).delete()
        return render(request, self.template_name)

company/templates/company/company_delete_complete.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">面接企業削除</h2>
            <p>企業削除が完了しました。</p>
            <a href='{% url 'company:top' %}'>企業一覧へ</a>
        </div>
    </div>
</div>
{% endblock %}

company/templates/company/company_register.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">面接企業登録</h2>
            <p>面接を実施した企業、またはこれから面接を予定している企業名を登録して下さい。</p>
            <form method="post" action="">
            {% csrf_token %}
              <div class="form-group">
                  <p>{{ form.errors.company_name }}</p>
                  <label for="company_name">{{form.company_name.label}}</label>
                  {{form.company_name}}
              </div>
              <button type="submit" class="btn btn-success btn-lg btn-block">登録</button>
              <a href="{% url 'company:top' %}" class="login_link" >企業一覧へ</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

company/templates/company/company_register_complete.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">面接企業登録</h2>
            <p>企業登録が完了しました。</p>
            <a href='{% url 'company:top' %}'>企業一覧へ</a>
        </div>
    </div>
</div>
{% endblock %}

company/templates/company/company_update.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">面接企業名変更</h2>
            <p>企業名変更したい際は以下フォームに変更後の企業名を入力して下さい。</p>
            <form method="post" action="">
            {% csrf_token %}
              <div class="form-group">
                  <p>{{ form.errors.company_name }}</p>
                  <label for="company_name">{{form.company_name.label}}</label>
                  {{form.company_name}}
              </div>
              <button type="submit" class="btn btn-success btn-lg btn-block">変更</button>
              <a href="{% url 'company:top' %}" class="login_link" >企業一覧へ</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

company/templates/company/company_update_complete.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">面接企業名変更</h2>
            <p>企業名変更が完了しました。</p>
            <a href='{% url 'company:top' %}'>企業一覧へ</a>
        </div>
    </div>
</div>
{% endblock %}

company/templates/company/top.html
{% extends "register/base.html" %}
{% block content %}
<h2 class="login_title">面接企業一覧</h2>
<p class="text-center main_contets margin_auto">面接は事前の準備が大変重要です。その為にも、面接を実施した後の振り返りをしっかり行い、次の面接に活かしていきましょう！</p>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">企業名</th>
      <th scope="col">面接振り返り</th>
      <th scope="col">企業名変更</th>
      <th scope="col">削除</th>
    </tr>
  </thead>
  <tbody>
  {% for company in companies %}
    <tr>
      <th scope="row">{{ company.company_name }}</th>
      <td><a href="{% url 'interview:top' company.id %}">振り返り</a></td>
      <td><a href="{% url 'company:update' company.id %}">変更</a></td>
      <td><a href="#" data-toggle="modal" data-target="#exampleModal{{ company.id }}">削除</a></td>
        <!-- 削除モーダル -->
        <div class="modal fade" id="exampleModal{{ company.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">削除確認</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                {{ company.company_name }}を本当に削除しますか？
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
                <a class="btn btn-danger" href="{% url "company:delete" company.id %}" role="button">削除</a>
              </div>
            </div>
          </div>
        </div>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}