answer/urls.py
from django.urls import path
from . import views

app_name = 'answer'

urlpatterns = [
    path('', views.AnswerTop.as_view(), name='top'),
    path('register', views.AnswerRegister.as_view(), name='register'),
    path('register_complete', views.AnswerRegisterComplete.as_view(), name='register_complete'),
    path('update/<int:pk>', views.AnswerUpdate.as_view(), name='update'),
    path('update_complete', views.AnswerUpdateComplete.as_view(), name='update_complete'),
    path('delete/<int:pk>', views.AnswerDelete.as_view(), name='delete'),
]

interview/urls.py
from django.urls import path
from . import views

app_name = 'interview'

urlpatterns = [
    path('<int:pk>', views.InterviewTop.as_view(), name='top'),
    path('register/<int:pk>', views.InterviewRegister.as_view(), name='register'),
    path('register_complete', views.InterviewRegisterComplete.as_view(), name='register_complete'),
    path('update/<int:pk>', views.InterviewUpdate.as_view(), name='update'),
    path('update_complete', views.InterviewUpdateComplete.as_view(), name='update_complete'),
    path('delete/<int:pk>', views.InterviewDelete.as_view(), name='delete'),
]

jobchange/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('company/', include('company.urls')),
    path('interview/', include('interview.urls')),
    path('answer/', include('answer.urls')),
]

interview/models.py
from django.db import models
from company.models import Company

class Interview(models.Model):
    company_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    selection_phase = models.CharField(max_length=200, null=True, blank=True)
    selection_date = models.DateTimeField(null=True, blank=True)
    question = models.TextField(null=True, blank=True)
    reflection = models.TextField(null=True, blank=True)
    other = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

interview/forms.py
from django import forms
from .models import Interview

class InterviewRegisterForm(forms.ModelForm):

    class Meta:
        model = Interview
        fields = (
            'selection_phase',
            'selection_date',
            'question',
            'reflection',
            'other',
        )

    selection_phase = forms.CharField(
        label='選考フェーズ',
        max_length=200,
        required=False,
        widget=forms.TextInput(attrs={'placeholder':'選考フェーズ', 'class':'form-control'})
    )
    selection_date = forms.DateTimeField(
        label='選考日程',
        required=False,
        widget = forms.DateInput(attrs={"type": "date", 'placeholder': '選考日程', 'class': 'form-control'})
    )
    question = forms.CharField(
        label='質問',
        required=False,
        widget=forms.Textarea(attrs={'placeholder': '質問', 'class': 'form-control'})
    )
    reflection = forms.CharField(
        label='振り返り',
        required=False,
        widget=forms.Textarea(attrs={'placeholder': '振り返り', 'class': 'form-control'})
    )
    other = forms.CharField(
        label='その他',
        required=False,
        widget=forms.Textarea(attrs={'placeholder': 'その他', 'class': 'form-control'})
    )

class InterviewUpdateForm(forms.ModelForm):

    class Meta:
        model = Interview
        fields = (
            'selection_phase',
            'selection_date',
            'question',
            'reflection',
            'other',
        )

    selection_phase = forms.CharField(
        label='選考フェーズ',
        max_length=200,
        required=False,
        widget=forms.TextInput(attrs={'placeholder': '選考フェーズ', 'class': 'form-control'})
    )
    selection_date = forms.DateTimeField(
        label='選考日程',
        required=False,
        widget = forms.DateInput(attrs={"type": "date", 'placeholder': '選考日程', 'class': 'form-control'})
    )
    question = forms.CharField(
        label='質問',
        required=False,
        widget=forms.Textarea(attrs={'placeholder': '質問', 'class': 'form-control'})
    )
    reflection = forms.CharField(
        label='振り返り',
        required=False,
        widget=forms.Textarea(attrs={'placeholder': '振り返り', 'class': 'form-control'})
    )
    other = forms.CharField(
        label='その他',
        required=False,
        widget=forms.Textarea(attrs={'placeholder': 'その他', 'class': 'form-control'})
    )

interview/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.shortcuts import redirect
from django.views import generic
from company.models import Company
from .models import Interview
from .forms import InterviewRegisterForm, InterviewUpdateForm

User = get_user_model()

class InterviewTop(generic.TemplateView):
    template_name = 'interview/top.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # company_id
        pk = self.kwargs['pk']
        context['company'] = Company.objects.get(id=pk)
        context['interviewes'] = Interview.objects.filter(company_id=pk).values
        return context


class InterviewRegister(generic.View):
    form_class = InterviewRegisterForm
    template_name = 'interview/interview_register.html'

    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        company = Company.objects.get(id=pk)
        form = self.form_class
        return render(request, self.template_name, {'form': form, 'company': company})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            pk = self.kwargs['pk']
            company = Company.objects.get(id=pk)
            selection_phase = form.cleaned_data['selection_phase']
            selection_date = form.cleaned_data['selection_date']
            question = form.cleaned_data['question']
            reflection = form.cleaned_data['reflection']
            other = form.cleaned_data['other']
            Interview.objects.create(
                company_id=company,
                selection_phase=selection_phase,
                selection_date=selection_date,
                question=question,
                reflection=reflection,
                other=other,
            )
            return render(request, 'interview/interview_register_complete.html', {'company_id': company.id})
        return render(request, self.template_name, {'form': form})


class InterviewRegisterComplete(generic.TemplateView):
    template_name = 'interview/interview_register_complete.html'


class InterviewUpdate(generic.TemplateView):
    form_class = InterviewUpdateForm
    template_name = 'interview/interview_update.html'

    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        interview = Interview.objects.get(id=pk)
        interview_obj = interview
        form = self.form_class(instance=interview)
        return render(request, self.template_name, {'form': form, 'interview_obj': interview_obj})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            selection_phase = form.cleaned_data['selection_phase']
            selection_date = form.cleaned_data['selection_date']
            question = form.cleaned_data['question']
            reflection = form.cleaned_data['reflection']
            other = form.cleaned_data['other']
            pk = self.kwargs['pk']
            interview = Interview.objects.get(id=pk)
            interview.selection_phase = selection_phase
            interview.selection_date = selection_date
            interview.question = question
            interview.reflection = reflection
            interview.other = other
            interview.save()
            return render(request, 'interview/interview_update_complete.html', {'interview': interview})
        return render(request, self.template_name, {'form': form})


class InterviewUpdateComplete(generic.TemplateView):
    template_name = 'interview/interview_update_complete.html'


class InterviewDelete(generic.TemplateView):
    template_name = 'interview/interview_delete_complete.html'

    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        company = Interview.objects.get(id=pk)
        Interview.objects.get(id=pk).delete()
        return render(request, self.template_name, {'company': company})

interview/templates/interview/interview_delete_complete.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">面接振り返り削除</h2>
            <p>面接振り返り削除が完了しました。</p>
            <a href='{% url 'interview:top' company.company_id.id %}'>面接振り返り一覧へ</a>
        </div>
    </div>
</div>
{% endblock %}

interview/templates/interview/interview_register.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">面接振り返り登録</h2>
            <h5 class="login_title">{{ company.company_name }}</h5>
            <p>{{ company.company_name }}の面接の振り返りをしてみましょう！以下フォームに面接時の情報を入力して下さい。</p>
            <form method="post" action="">
            {% csrf_token %}
                <div class="form-group">
                    <p>{{ form.errors.selection_phase }}</p>
                  　<label for="company_name">{{form.selection_phase.label}}</label>
                  　{{form.selection_phase}}
              　</div>
                <div class="form-group">
                　  <p>{{ form.errors.selection_date }}</p>
                  　<label for="company_name">{{form.selection_date.label}}</label>
                  　{{form.selection_date}}
              　</div>
                <div class="form-group">
                　  <p>{{ form.errors.question }}</p>
                  　<label for="company_name">{{form.question.label}}</label>
                  　{{form.question}}
              　</div>
                <div class="form-group">
                　  <p>{{ form.errors.reflection }}</p>
                  　<label for="company_name">{{form.reflection.label}}</label>
                  　{{form.reflection}}
              　</div>
                <div class="form-group">
                　  <p>{{ form.errors.other }}</p>
                  　<label for="company_name">{{form.other.label}}</label>
                  　{{form.other}}
              　</div>
              <button type="submit" class="btn btn-success btn-lg btn-block">登録</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

interview/templates/interview/interview_register_complete.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">面接振り返り登録</h2>
            <p>面接振り返り登録が完了しました。</p>
            <a href='{% url 'interview:top' company_id %}'>振り返り一覧へ</a>
        </div>
    </div>
</div>
{% endblock %}

interview/templates/interview/interview_update.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">面接振り返り編集</h2>
            <h5 class="login_title">{{ interview_obj.company_id.company_name }}</h5>
            <p>{{ interview_obj.company_id.company_name }}の面接の振り返りをしてみましょう！以下フォームから面接時の情報を編集して下さい。</p>
            <form method="post" action="">
            {% csrf_token %}
                <div class="form-group">
                    <p>{{ form.errors.selection_phase }}</p>
                  　<label for="company_name">{{form.selection_phase.label}}</label>
                  　{{form.selection_phase}}
              　</div>
                <div class="form-group">
                　  <p>{{ form.errors.selection_date }}</p>
                  　<label for="company_name">{{form.selection_date.label}}</label>
                  　{{form.selection_date}}
              　</div>
                <div class="form-group">
                　  <p>{{ form.errors.question }}</p>
                  　<label for="company_name">{{form.question.label}}</label>
                  　{{form.question}}
              　</div>
                <div class="form-group">
                　  <p>{{ form.errors.reflection }}</p>
                  　<label for="company_name">{{form.reflection.label}}</label>
                  　{{form.reflection}}
              　</div>
                <div class="form-group">
                　  <p>{{ form.errors.other }}</p>
                  　<label for="company_name">{{form.other.label}}</label>
                  　{{form.other}}
              　</div>
              <button type="submit" class="btn btn-success btn-lg btn-block">更新</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

interview/templates/interview/interview_update_complete.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <div class="card col-md-6 margin_auto">
        <div class="card-body">
            <h2 class="login_title">面接振り返り編集</h2>
            <p>面接振り返り編集が完了しました。</p>
            <a href='{% url 'interview:top' interview.company_id.id %}'>面接振り返り一覧へ</a>
        </div>
    </div>
</div>
{% endblock %}

interview/templates/interview/top.html
{% extends "register/base.html" %}
{% block content %}
    <h2 class="login_title">面接振り返り</h2>
    <h5 class="login_title">{{ company.company_name }}</h5>
    <p class="text-center main_contets margin_auto">{{ company.company_name }}の面接を振り返ってみましょう！</p>
    <a class="btn btn-primary register_button_margin" href="{% url "interview:register" company.id  %}" role="button">新規登録</a>
    {% if interviewes %}
    {% for interview in interviewes %}
        <div class="card bg-light mb-3 margin_auto main_contets">
          <div class="card-header font-weight-bold text-center">
              {% if interview.selection_phase %}
                  {{ interview.selection_phase }}
              {% else %}
                  登録なし
              {% endif %}
          </div>
          <div class="card-body">
            <h5 class="card-title">★選考日程</h5>
            <p class="card-text font-weight-bold">
                {% if interview.selection_date %}
                  {{ interview.selection_date }}
              　{% else %}
                  登録なし
              　{% endif %}
            </p>
            <h5 class="card-title">★聞かれた質問・回答</h5>
            <p class="card-text font-weight-bold">
                {% if interview.question %}
                  {{ interview.question}}
              　{% else %}
                  登録なし
              　{% endif %}
            </p>
            <h5 class="card-title">★振り返り</h5>
            <p class="card-text font-weight-bold">
                {% if interview.reflection %}
                  {{ interview.reflection}}
              　{% else %}
                  登録なし
              　{% endif %}
            </p>
            <h5 class="card-title">★その他</h5>
            <p class="card-text font-weight-bold">
                {% if interview.other %}
                  {{ interview.other}}
              　{% else %}
                  登録なし
              　{% endif %}
            </p>
            <a class="btn btn-warning" href="{% url "interview:update" interview.id %}" role="button">変更</a>
            <a class="btn btn-danger" href="#" role="button" data-toggle="modal" data-target="#exampleModal{{ interview.id }}">削除</a>

          <!-- 削除モーダル -->
            <div class="modal fade" id="exampleModal{{ interview.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">削除確認</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                      {% if interview.selection_phase %}
                          {{ interview.selection_phase }}を本当に削除しますか？
                      {% else %}
                          本当に削除しますか？
                      {% endif %}
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
                    <a class="btn btn-danger" href="{% url "interview:delete" interview.id %}" role="button">削除</a>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
    {% endfor %}
    {% else %}
        <p class="text-center main_contets margin_auto">データがありません。</p>
    {% endif %}
{% endblock %}